//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FittSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_GYAKORLAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_GYAKORLAT()
        {
            this.F_EDZES_GYAKORLAT = new HashSet<F_EDZES_GYAKORLAT>();
        }
    
        public int GYAKORLAT_SK { get; set; }
        public int KATEGORIA_ID { get; set; }
        public string MEGNEVEZES { get; set; }
        public string LEIRAS { get; set; }
    
        public virtual D_KATEGORIA D_KATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_EDZES_GYAKORLAT> F_EDZES_GYAKORLAT { get; set; }
    }
}
