//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FittSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_EDZES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public F_EDZES()
        {
            this.F_EDZES_GYAKORLAT = new HashSet<F_EDZES_GYAKORLAT>();
        }
    
        public int EDZES_SK { get; set; }
        public decimal IDOTARTAM { get; set; }
        public System.DateTime KEZD_IDOPONT { get; set; }
        public System.DateTime BEF_IDOPONT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_EDZES_GYAKORLAT> F_EDZES_GYAKORLAT { get; set; }
    }
}
